# Generated by Django 4.2.18 on 2025-05-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0002_alter_personnel_categorie_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='etat_periode',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En Cours', 'En Cours'), ('Cloturée', 'Cloturée')], default='En attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='etat_trimestre',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En Cours', 'En Cours'), ('Cloturée', 'Cloturée')], default='En attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='trimestre',
            field=models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3'), ('Trimestre 4', 'Trimestre 4'), ('Trimestre 5', 'Trimestre 5'), ('Trimestre 6', 'Trimestre 6')], max_length=20),
        ),
    ]
