# Generated by Django 4.2.18 on 2025-05-21 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0004_alter_periode_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periode',
            name='date_fin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='periode',
            name='periode',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7'), ('P8', 'P8')], max_length=20),
        ),
    ]
