# Generated by Django 4.2.18 on 2025-05-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0005_periode_date_debut_periode_date_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliberation_annuelle_finalite',
            name='finalite',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='eleve_note_type',
            name='sigle',
            field=models.CharField(choices=[('T.J', 'T.J'), ('Ex.', 'Ex.')], max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve_note_type',
            name='type',
            field=models.CharField(choices=[('Travail Journalier', 'Travail Journalier'), ('Examen', 'Examen')], max_length=250),
        ),
    ]
