# Generated by Django 4.2.18 on 2025-05-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0007_remove_deliberation_annuelle_resultat_id_trimestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliberation_annuelle_condition',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='deliberation_annuelle_condition',
            name='sigle',
        ),
        migrations.AddField(
            model_name='deliberation_annuelle_finalite',
            name='sigle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
