# Generated by Django 4.2.18 on 2025-05-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0009_alter_deliberation_annuelle_condition_pourcentage_requis_reussite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliberation_annuelle_condition',
            old_name='pourcentage_requis_reussite',
            new_name='id_mention',
        ),
    ]
