# Generated by Django 4.2.18 on 2025-06-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0012_annee_periode_etat_periode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annee_periode',
            name='id_trimestre_annee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee_trimestre'),
            preserve_default=False,
        ),
    ]
