# Generated by Django 4.2.18 on 2025-06-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0017_alter_evaluation_id_periode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve_conduite',
            name='id_periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee_periode'),
        ),
        migrations.AlterField(
            model_name='eleve_conduite',
            name='id_trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee_trimestre'),
        ),
        migrations.AlterField(
            model_name='eleve_note',
            name='id_periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee_periode'),
        ),
        migrations.AlterField(
            model_name='eleve_note',
            name='id_trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee_trimestre'),
        ),
    ]
