# Generated by Django 4.2.18 on 2025-06-03 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0018_alter_eleve_conduite_id_periode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliberation_periodique_resultat',
            name='id_periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee_periode'),
        ),
        migrations.AlterField(
            model_name='deliberation_periodique_resultat',
            name='id_trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee_trimestre'),
        ),
        migrations.AlterField(
            model_name='deliberation_trimistrielle_resultat',
            name='id_trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee_trimestre'),
        ),
    ]
