# Generated by Django 4.2.18 on 2025-06-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0019_alter_deliberation_periodique_resultat_id_periode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annee_trimestre',
            old_name='etat_annee',
            new_name='etat_trimestre',
        ),
    ]
