# Generated by Django 4.2.18 on 2025-06-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0020_rename_etat_annee_annee_trimestre_etat_trimestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve_note',
            name='note_repechage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eleve_note_type',
            name='sigle',
            field=models.CharField(choices=[('T.J', 'T.J'), ('Ex.', 'Ex.'), ('DàD', 'DàD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve_note_type',
            name='type',
            field=models.CharField(choices=[('Travail Journalier', 'Travail Journalier'), ('Examen', 'Examen'), ('Devoir', 'Devoir')], max_length=250),
        ),
    ]
