# Generated by Django 4.2.18 on 2025-06-25 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0021_eleve_note_note_repechage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliberation_repechage_resultat',
            fields=[
                ('id_repechage', models.AutoField(primary_key=True, serialize=False)),
                ('pourcent_par_cours', models.FloatField()),
                ('valid_repechage', models.BooleanField(default=False)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cours_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.cours_par_classe')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.deliberation_annuelle_finalite')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.session')),
            ],
            options={
                'verbose_name': 'Résultat de délibération repechage',
                'db_table': 'deliberation_repechage_resultats',
            },
        ),
    ]
