# Generated by Django 4.2.18 on 2025-06-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0022_deliberation_repechage_resultat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliberation_repechage_resultat',
            name='pourcent_par_cours',
        ),
    ]
