# Generated by Django 4.2.18 on 2025-06-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0023_remove_deliberation_repechage_resultat_pourcent_par_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(choices=[('Repêchage', 'Repêchage'), ('session ordinaire', 'session ordinaire')], max_length=20, unique=True),
        ),
    ]
