# Generated by Django 4.2.18 on 2025-06-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0024_alter_session_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliberation_repechage_resultat',
            old_name='id_decision',
            new_name='id_finalite',
        ),
    ]
