# Generated by Django 4.2.18 on 2025-07-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0025_rename_id_decision_deliberation_repechage_resultat_id_finalite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliberation_type',
            name='type',
            field=models.CharField(choices=[('par période', 'par période'), ('Par trimestre', 'Par trimestre'), ('Par année', 'Par année'), ('Par repêchage', 'Par repêchage')], max_length=200, unique=True),
        ),
    ]
