# Generated by Django 4.2.18 on 2025-07-29 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0029_classe_cycle_actif_ordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe_cycle',
            name='cycle',
            field=models.CharField(choices=[('Maternelle', 'Maternelle'), ('Fondamentale', 'Fondamentale'), ('Post Fondamentale', 'Post Fondamentale')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='classe_cycle',
            name='id_cycle',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deliberation_annuelle_condition',
            name='max_echecs_acceptable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliberation_annuelle_condition',
            name='seuil_profondeur_echec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='date_naissance',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 7, 29, 6, 35, 47, 109276, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
