# Generated by Django 4.2.18 on 2025-08-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0031_banque_compte_variable_variable_categorie_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variable_categorie',
            new_name='VariableCategorie',
        ),
        migrations.RenameModel(
            old_name='Variable_datebutoire',
            new_name='VariableDatebutoire',
        ),
        migrations.RenameModel(
            old_name='Variable_derogation',
            new_name='VariableDerogation',
        ),
        migrations.RenameModel(
            old_name='Variable_prix',
            new_name='VariablePrix',
        ),
    ]
