# Generated by Django 4.2.18 on 2025-08-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0034_rename_id_classe_eleve_reduction_prix_id_classe_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableprix',
            name='prix',
            field=models.PositiveIntegerField(),
        ),
    ]
