# Generated by Django 4.2.18 on 2025-08-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0036_remove_variablederogation_id_variable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variablederogation',
            old_name='id_datebutoire',
            new_name='id_derogation',
        ),
    ]
