# Generated by Django 4.2.18 on 2025-08-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0038_rename_date_butoire_variablederogation_date_derogation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve_reduction_prix',
            name='id_variable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.variable'),
            preserve_default=False,
        ),
    ]
