# Generated by Django 4.2.18 on 2025-08-21 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0040_variablederogation_id_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve_reduction_prix',
            name='id_eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='id_eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve'),
        ),
    ]
