# Generated by Django 4.2.18 on 2025-08-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0042_rename_poucentage_eleve_reduction_prix_pourcentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='bordereau',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
