# Generated by Django 4.2.18 on 2025-08-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0043_alter_paiement_bordereau'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='id_banque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.banque'),
            preserve_default=False,
        ),
    ]
