# Generated by Django 4.2.18 on 2025-08-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0045_alter_paiement_bordereau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='bordereau',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/minerval/'),
        ),
    ]
