# Generated by Django 4.2.18 on 2025-09-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0049_alter_module_module_alter_module_url_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periode',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='periode',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='periode',
            name='etat_periode',
        ),
        migrations.RemoveField(
            model_name='trimestre',
            name='date_cloture',
        ),
        migrations.RemoveField(
            model_name='trimestre',
            name='date_ouverture',
        ),
        migrations.RemoveField(
            model_name='trimestre',
            name='etat_trimestre',
        ),
    ]
