# Generated by Django 4.2.18 on 2025-09-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0050_remove_periode_date_debut_remove_periode_date_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='periode',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7'), ('P8', 'P8'), ('P9', 'P9')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='trimestre',
            field=models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3'), ('Trimestre 4', 'Trimestre 4'), ('Trimestre 5', 'Trimestre 5'), ('Trimestre 6', 'Trimestre 6'), ('Trimestre 7', 'Trimestre 7')], max_length=20),
        ),
    ]
