# Generated by Django 4.2.18 on 2026-02-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0055_remove_deliberation_examen_resultat_id_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours_par_classe',
            name='is_second_semester',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='trimestre',
            table='trimestre',
        ),
    ]
