from .eleves.eleve import *
from .evaluations.note import *
from .enseignmnts.matiere import *
from .annee import *
from .campus import *
from .classe import *
from .ecole import * 
from .horaire import *
from .personnel import *
from .mention import * 
from .salle import * 
from .models_import import * 
from .module import *
from .recouvrement import *
from .country_structure import *
