# Generated by Django 4.2.18 on 2025-05-15 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id_annee', models.AutoField(primary_key=True, serialize=False)),
                ('debut', models.IntegerField(blank=True, null=True)),
                ('fin', models.IntegerField(blank=True, null=True)),
                ('annee', models.CharField(max_length=20)),
                ('etat_annee', models.CharField(choices=[('En attente', 'En attente'), ('En Cours', 'En Cours'), ('Cloturée', 'Cloturée')], default='En attente', max_length=50)),
                ('date_ouverture', models.DateField()),
                ('date_cloture', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Année_scolaire',
                'db_table': 'annee',
            },
        ),
        migrations.CreateModel(
            name='Attribution_type',
            fields=[
                ('id_attribution_type', models.AutoField(primary_key=True, serialize=False)),
                ('attribution_type', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Attribution de cours',
                'db_table': 'attribution_type',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id_campus', models.AutoField(primary_key=True, serialize=False)),
                ('campus', models.CharField(max_length=50, unique=True)),
                ('adresse', models.CharField(max_length=255)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'db_table': 'campus',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('classe', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Classe_active',
            fields=[
                ('id_classe_active', models.AutoField(primary_key=True, serialize=False)),
                ('groupe', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True)),
                ('isTerminale', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe')),
            ],
            options={
                'verbose_name': 'Classe Active',
                'db_table': 'classe_active',
            },
        ),
        migrations.CreateModel(
            name='Classe_cycle',
            fields=[
                ('id_cycle', models.AutoField(db_column='id_cycle', primary_key=True, serialize=False)),
                ('cycle', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cycle de Classe',
                'db_table': 'classe_cycle',
            },
        ),
        migrations.CreateModel(
            name='Classe_cycle_actif',
            fields=[
                ('id_cycle_actif', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
            ],
            options={
                'verbose_name': 'Cycle Actif',
                'db_table': 'classe_cycle_actif',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id_cours', models.AutoField(primary_key=True, serialize=False)),
                ('cours', models.CharField(max_length=150)),
                ('code_cours', models.CharField(blank=True, max_length=15, null=True)),
                ('domaine', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'db_table': 'cours',
            },
        ),
        migrations.CreateModel(
            name='Cours_par_classe',
            fields=[
                ('id_cours_classe', models.AutoField(primary_key=True, serialize=False)),
                ('ponderation', models.IntegerField(blank=True, null=True)),
                ('CM', models.IntegerField(blank=True, null=True)),
                ('TD', models.IntegerField(blank=True, null=True)),
                ('TP', models.IntegerField(blank=True, null=True)),
                ('TPE', models.IntegerField(blank=True, null=True)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.cours')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
            ],
            options={
                'verbose_name': 'Cours_par_classe',
                'db_table': 'cours_par_classe',
            },
        ),
        migrations.CreateModel(
            name='Deliberation_annuelle_condition',
            fields=[
                ('id_decision', models.AutoField(primary_key=True, serialize=False)),
                ('sigle', models.CharField(max_length=50)),
                ('decision', models.CharField(max_length=50)),
                ('pourcentage_requis_reussite', models.IntegerField()),
                ('max_echecs_acceptable', models.IntegerField()),
                ('seuil_profondeur_echec', models.IntegerField()),
                ('sanction_disciplinaire', models.CharField(blank=True, max_length=100, null=True)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
            ],
            options={
                'verbose_name': 'Condition_délibération annuelle',
                'db_table': 'deliberation_annuelle_conditions',
            },
        ),
        migrations.CreateModel(
            name='Deliberation_annuelle_finalite',
            fields=[
                ('id_finalite', models.AutoField(primary_key=True, serialize=False)),
                ('finalite', models.CharField(max_length=200)),
                ('droit_avancement', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Finalité_délibération',
                'db_table': 'deliberation_annuelle_finalites',
            },
        ),
        migrations.CreateModel(
            name='Deliberation_type',
            fields=[
                ('id_deliberation_type', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'deliberation_type',
                'db_table': 'deliberation_type',
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id_diplome', models.AutoField(primary_key=True, serialize=False)),
                ('diplome', models.CharField(max_length=50, unique=True)),
                ('sigle', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'diplome',
                'db_table': 'diplome',
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id_eleve', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=50)),
                ('etat_civil', models.CharField(blank=True, choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Autres', 'Autres')], default='Célibataire', max_length=50, null=True)),
                ('code_eleve', models.CharField(blank=True, max_length=250, null=True)),
                ('code_annee', models.IntegerField(blank=True, default=0, null=True)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_pere', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('prenom_pere', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('nom_mere', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('prenom_mere', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_parent', models.EmailField(blank=True, max_length=254, null=True)),
                ('password_parent', models.CharField(blank=True, max_length=300, null=True)),
                ('password', models.CharField(blank=True, max_length=300, null=True)),
                ('tutaire', models.CharField(blank=True, max_length=250, null=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BI')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('naissance_region', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('naissance_pays', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('naissance_province', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('naissance_commune', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('naissance_zone', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('province_actuelle', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('commune_actuelle', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('zone_actuelle', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to='logos/eleves/')),
                ('nationalite', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('professionPere', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('professionMere', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('profsion_tutaire', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('IDelivranceLieuEtDate', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('code_secret_parent', models.CharField(blank=True, max_length=250, null=True)),
                ('code_secret_eleve', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'eleve',
            },
        ),
        migrations.CreateModel(
            name='Eleve_note_type',
            fields=[
                ('id_type_note', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=250)),
                ('sigle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'eleve_note_type',
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id_horaire', models.AutoField(primary_key=True, serialize=False)),
                ('jour', models.CharField(max_length=100)),
                ('debut', models.CharField(max_length=100)),
                ('fin', models.CharField(max_length=100)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.cours_par_classe')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
            ],
            options={
                'db_table': 'horaire',
            },
        ),
        migrations.CreateModel(
            name='Horaire_type',
            fields=[
                ('id_horaire_type', models.AutoField(primary_key=True, serialize=False)),
                ('horaire_type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'horaire_type',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id_ecole', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ecole', models.CharField(max_length=250, unique=True)),
                ('sigle', models.CharField(max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('domaine', models.CharField(blank=True, max_length=50)),
                ('site', models.URLField(blank=True, max_length=50)),
                ('logo_ecole', models.ImageField(blank=True, null=True, upload_to='logos/ecole/')),
                ('logo_ministere', models.ImageField(blank=True, null=True, upload_to='logos/ministere/')),
                ('siege', models.CharField(blank=True, max_length=50)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('representant', models.CharField(blank=True, max_length=50)),
                ('b_postale', models.CharField(blank=True, max_length=50)),
                ('emplacement', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'ecole',
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id_mention', models.AutoField(primary_key=True, serialize=False)),
                ('mention', models.CharField(max_length=30, unique=True)),
                ('abbreviation', models.CharField(max_length=5)),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
            ],
            options={
                'db_table': 'mention',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id_module', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('Administration', 'Administration'), ('Inscription', 'Inscription'), ('Evaluation', 'Evaluation'), ('Enseignement', 'Enseignement'), ('Institeur et son Espace', 'Institeur et son Espace'), ('Recouvrement', 'Recouvrement'), ('Portail des parents', 'Portail des parents'), ('Archive', 'Archive')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url_name', models.CharField(blank=True, choices=[('home_administration', 'home_administration'), ('home_inscription', 'home_inscription'), ('home_evaluation', 'home_evaluation'), ('home_enseignement', 'home_enseignement'), ('home_zone_pedagogique', 'home_zone_pedagogique'), ('home_recouvrement', 'home_recouvrement'), ('home_parent', 'home_parent'), ('home_archive', 'home_archive')], max_length=100, null=True)),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id_personnel', models.AutoField(primary_key=True, serialize=False)),
                ('codeAnnee', models.CharField(blank=True, max_length=200, null=True)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=22)),
                ('etat_civil', models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Autres', 'Autres')], default='Célibataire', max_length=200)),
                ('type_identite', models.CharField(blank=True, max_length=200)),
                ('numero_identite', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BI')),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('pays', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=200)),
                ('commune', models.CharField(blank=True, max_length=200)),
                ('code_secret', models.TextField(blank=True, max_length=150, null=True)),
                ('zone', models.CharField(blank=True, max_length=200)),
                ('addresse', models.CharField(blank=True, max_length=200)),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to='logos/personnel/')),
                ('isMaitresse', models.BooleanField(default=False)),
                ('isInstiteur', models.BooleanField(default=False)),
                ('isDAF', models.BooleanField(default=False)),
                ('isDirecteur', models.BooleanField(default=False)),
                ('isUser', models.BooleanField(default=False)),
                ('en_fonction', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'personnel',
                'db_table': 'personnel',
            },
        ),
        migrations.CreateModel(
            name='Personnel_categorie',
            fields=[
                ('id_personnel_category', models.AutoField(primary_key=True, serialize=False)),
                ('categorie', models.CharField(max_length=50, unique=True)),
                ('sigle', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'personnel_categorie',
                'db_table': 'personnel_categorie',
            },
        ),
        migrations.CreateModel(
            name='PersonnelType',
            fields=[
                ('id_type_personnel', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, unique=True)),
                ('sigle', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'personnel_type',
                'db_table': 'personnel_type',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'session',
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id_specialite', models.AutoField(primary_key=True, serialize=False)),
                ('specialite', models.CharField(max_length=200)),
                ('sigle', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'specialite',
                'db_table': 'specialite',
            },
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id_trimestre', models.AutoField(primary_key=True, serialize=False)),
                ('trimestre', models.CharField(max_length=20)),
                ('etat_trimestre', models.CharField(choices=[('En attente', 'En attente'), ('En Cours', 'En Cours'), ('Cloturée', 'Cloturée')], default='En cours', max_length=50)),
                ('date_ouverture', models.DateField()),
                ('date_cloture', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trimestre',
                'db_table': 'Trimestre',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id_vacation', models.AutoField(primary_key=True, serialize=False)),
                ('vacation', models.CharField(max_length=20)),
                ('sigle', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'vacation',
                'db_table': 'vacation',
            },
        ),
        migrations.CreateModel(
            name='Users_other_module',
            fields=[
                ('id_user_per_module', models.AutoField(primary_key=True, serialize=False)),
                ('id_module', models.IntegerField()),
                ('user', models.BooleanField(default=False)),
                ('id_personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.personnel')),
            ],
            options={
                'db_table': 'users_other_module',
            },
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id_user_module', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.personnel')),
            ],
            options={
                'db_table': 'user_module',
            },
        ),
        migrations.CreateModel(
            name='User_enseignement',
            fields=[
                ('id_user_enseignant', models.AutoField(primary_key=True, serialize=False)),
                ('canModify', models.BooleanField(default=False)),
                ('canOnlyView', models.BooleanField(default=False)),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.personnel')),
            ],
            options={
                'db_table': 'user_enseignement',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id_salle', models.AutoField(primary_key=True, serialize=False)),
                ('salle', models.CharField(max_length=250)),
                ('partage', models.BooleanField(default=False)),
                ('capacite', models.IntegerField()),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
            ],
            options={
                'verbose_name': 'salle',
                'db_table': 'salle',
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id_prestation', models.AutoField(primary_key=True, serialize=False)),
                ('heureD', models.CharField(max_length=20)),
                ('heureF', models.CharField(max_length=20)),
                ('id_horaire', models.IntegerField()),
                ('id_etudiant', models.IntegerField()),
                ('id_personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.personnel')),
            ],
            options={
                'verbose_name': 'prestation',
                'db_table': 'prestation',
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='id_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.personnel_categorie'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='id_diplome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.diplome'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='id_personnel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.personneltype'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='id_specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.specialite'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='id_vacation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.vacation'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id_periode', models.AutoField(primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=20)),
                ('etat_periode', models.CharField(choices=[('En attente', 'En attente'), ('En Cours', 'En Cours'), ('Cloturée', 'Cloturée')], default='En cours', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('id_trimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.trimestre')),
            ],
            options={
                'verbose_name': 'periode',
                'db_table': 'periode',
            },
        ),
        migrations.CreateModel(
            name='Horaire_presence',
            fields=[
                ('id_horaire_presence', models.AutoField(primary_key=True, serialize=False)),
                ('present_ou_absent', models.BooleanField()),
                ('date_presence', models.DateField()),
                ('si_absent_motif', models.CharField(max_length=255, null=True)),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve')),
                ('id_horaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.horaire')),
            ],
            options={
                'db_table': 'horaire_presence',
            },
        ),
        migrations.AddField(
            model_name='horaire',
            name='id_horaire_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.horaire_type'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_evaluation', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('ponderer_eval', models.PositiveIntegerField(default=0)),
                ('date_eval', models.DateField()),
                ('date_soumission', models.DateField(blank=True, null=True)),
                ('contenu_evaluation', models.FileField(upload_to='evaluations/')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe_active', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cours_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.cours_par_classe')),
                ('id_cycle_actif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.periode')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.session')),
                ('id_trimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.trimestre')),
                ('id_type_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve_note_type')),
            ],
            options={
                'db_table': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='Eleve_note',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('date_saisie', models.DateField(auto_now_add=True)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe_active', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cours_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.cours_par_classe')),
                ('id_cycle_actif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve')),
                ('id_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.evaluation')),
                ('id_periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.periode')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.session')),
                ('id_trimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.trimestre')),
                ('id_type_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve_note_type')),
            ],
            options={
                'db_table': 'eleve_note',
            },
        ),
        migrations.CreateModel(
            name='Eleve_inscription',
            fields=[
                ('id_inscription', models.AutoField(primary_key=True, serialize=False)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('redoublement', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('isDelegue', models.BooleanField(default=False)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_classe_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve')),
                ('id_trimestre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.trimestre')),
            ],
            options={
                'db_table': 'eleve_inscription',
            },
        ),
        migrations.CreateModel(
            name='Eleve_conduite',
            fields=[
                ('id_eleve_conduite', models.AutoField(primary_key=True, serialize=False)),
                ('motif', models.CharField(max_length=255)),
                ('quote', models.PositiveIntegerField(default=0)),
                ('date_enregistrement', models.DateField(auto_now_add=True)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve')),
                ('id_horaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.horaire')),
                ('id_periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.periode')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.session')),
                ('id_trimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.trimestre')),
            ],
            options={
                'db_table': 'eleve_conduite',
            },
        ),
        migrations.CreateModel(
            name='Deliberation_trimistrielle_resultat',
            fields=[
                ('id_deliberation', models.AutoField(primary_key=True, serialize=False)),
                ('pourcentage', models.FloatField()),
                ('place', models.CharField(max_length=200)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve')),
                ('id_trimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.trimestre')),
            ],
            options={
                'verbose_name': 'Résultat de délibération trimestrielle',
                'db_table': 'deliberation_trimistrielle_resultats',
            },
        ),
        migrations.CreateModel(
            name='Deliberation_periodique_resultat',
            fields=[
                ('id_deliberation', models.AutoField(primary_key=True, serialize=False)),
                ('pourcentage', models.FloatField()),
                ('place', models.CharField(max_length=200)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve')),
                ('id_periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.periode')),
                ('id_trimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.trimestre')),
            ],
            options={
                'verbose_name': 'Résultat de délibération périodique',
                'db_table': 'deliberation_periodique_resultats',
            },
        ),
        migrations.CreateModel(
            name='Deliberation_annuelle_resultat',
            fields=[
                ('id_deliberation', models.AutoField(primary_key=True, serialize=False)),
                ('pourcentage', models.FloatField()),
                ('place', models.CharField(max_length=200)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.deliberation_annuelle_condition')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve')),
                ('id_mention', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.mention')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.session')),
                ('id_trimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.trimestre')),
            ],
            options={
                'verbose_name': 'Résultat de délibération annuelle',
                'db_table': 'deliberation_annuelle_resultats',
            },
        ),
        migrations.AddField(
            model_name='deliberation_annuelle_condition',
            name='id_finalite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.deliberation_annuelle_finalite'),
        ),
        migrations.CreateModel(
            name='Classe_section',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=100)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
            ],
            options={
                'verbose_name': 'section classes',
                'db_table': 'classe_section',
            },
        ),
        migrations.CreateModel(
            name='Classe_deliberation',
            fields=[
                ('id_deliberation', models.AutoField(primary_key=True, serialize=False)),
                ('date_deliberation', models.DateField()),
                ('showResults', models.BooleanField()),
                ('showsResultsEnOrdre', models.BooleanField()),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.session')),
            ],
            options={
                'verbose_name': 'Délibération de classe',
                'db_table': 'classe_deliberation',
            },
        ),
        migrations.CreateModel(
            name='Classe_active_responsable',
            fields=[
                ('id_classe_active_resp', models.AutoField(primary_key=True, serialize=False)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.personnel')),
            ],
            options={
                'verbose_name': 'Responsable de Classe',
                'db_table': 'classe_active_responsable',
            },
        ),
        migrations.AddField(
            model_name='classe_active',
            name='cycle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif'),
        ),
        migrations.AddField(
            model_name='classe_active',
            name='id_annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee'),
        ),
        migrations.AddField(
            model_name='classe_active',
            name='id_campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus'),
        ),
        migrations.CreateModel(
            name='Attribution_cours',
            fields=[
                ('id_attribution', models.AutoField(primary_key=True, serialize=False)),
                ('attribution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.attribution_type')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.cours_par_classe')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.personnel')),
            ],
            options={
                'verbose_name': 'Attribution de cours',
                'db_table': 'attribution_cours',
            },
        ),
        migrations.CreateModel(
            name='Annee_trimestre',
            fields=[
                ('id_trimestre', models.AutoField(primary_key=True, serialize=False)),
                ('debut', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.trimestre')),
            ],
            options={
                'verbose_name': 'Trimestre_AnnéeScolaire',
                'db_table': 'annee_trimestre',
            },
        ),
        migrations.CreateModel(
            name='Annee_periode',
            fields=[
                ('id_periode', models.AutoField(primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=50)),
                ('debut', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
            ],
            options={
                'verbose_name': 'Période_AnnéeScolaire',
                'db_table': 'annee_periode',
            },
        ),
        migrations.CreateModel(
            name='Cours_par_cycle',
            fields=[
                ('id_cours_cycle', models.AutoField(primary_key=True, serialize=False)),
                ('cours_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.cours')),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
            ],
            options={
                'verbose_name': 'Cours_par_cycle',
                'db_table': 'cours_par_cycle',
                'unique_together': {('cours_id', 'cycle_id', 'id_annee')},
            },
        ),
    ]
