# Generated by Django 4.2.18 on 2026-04-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0001_add_id_etablissement_to_attribution_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieOperation',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('type_operation', models.CharField(choices=[('ENTREE', "Entrée d'argent"), ('SORTIE', "Sortie d'argent")], max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_pays', models.IntegerField(blank=True, null=True)),
                ('id_etablissement', models.IntegerField(blank=True, null=True)),
                ('idCampus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'recouvrement_categorie_operation',
                'ordering': ['type_operation', 'nom'],
                'unique_together': {('type_operation', 'nom', 'id_pays')},
            },
        ),
        migrations.AddField(
            model_name='banque',
            name='id_etablissement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='id_etablissement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eleve_reduction_prix',
            name='id_etablissement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='id_etablissement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='id_etablissement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variablecategorie',
            name='id_etablissement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variabledatebutoire',
            name='id_etablissement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variablederogation',
            name='id_etablissement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variableprix',
            name='id_etablissement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='url_name',
            field=models.CharField(blank=True, choices=[('dashboard_administration', 'dashboard_administration'), ('dashboard_scolarite', 'dashboard_scolarite'), ('dashboard_evaluations', 'dashboard_evaluations'), ('dashboard_enseignements', 'dashboard_enseignements'), ('dashboard_recouvrement', 'dashboard_recouvrement')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PenaliteConfig',
            fields=[
                ('id_penalite_regle', models.AutoField(primary_key=True, serialize=False)),
                ('groupe', models.CharField(blank=True, max_length=5, null=True)),
                ('type_penalite', models.CharField(choices=[('FORFAIT', 'Forfait'), ('POURCENTAGE', 'Pourcentage')], max_length=20)),
                ('valeur', models.FloatField()),
                ('plafond', models.PositiveIntegerField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('id_pays', models.IntegerField(blank=True, null=True)),
                ('id_etablissement', models.IntegerField(blank=True, null=True)),
                ('idCampus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_annee', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_classe', models.ForeignKey(blank=True, db_column='classe_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe')),
                ('id_cycle', models.ForeignKey(blank=True, db_column='id_cycle_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.cycle')),
                ('id_variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.variable')),
                ('section', models.ForeignKey(blank=True, db_column='section_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MonEcole_app.section')),
            ],
            options={
                'db_table': 'recouvrement_penalite',
            },
        ),
        migrations.CreateModel(
            name='OperationCaisse',
            fields=[
                ('id_operation', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.IntegerField(verbose_name='Montant')),
                ('date_operation', models.DateField(verbose_name='Date')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('source_beneficiaire', models.CharField(blank=True, help_text='Source (entrée) ou bénéficiaire (sortie)', max_length=200, null=True)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement'), ('AUTRE', 'Autre')], default='ESPECES', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('id_pays', models.IntegerField(blank=True, null=True)),
                ('id_etablissement', models.IntegerField(blank=True, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='MonEcole_app.categorieoperation')),
                ('idCampus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations',
                'db_table': 'recouvrement_operation',
                'ordering': ['-date_operation', '-date_enregistrement'],
                'indexes': [models.Index(fields=['id_annee', 'idCampus', 'date_operation'], name='recouvremen_id_anne_2148e6_idx')],
            },
        ),
    ]
