# Generated by Django 4.2.18 on 2025-05-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel_categorie',
            options={'verbose_name': 'Categorie du personnel'},
        ),
        migrations.AlterModelOptions(
            name='personneltype',
            options={'verbose_name': 'Type du personnel'},
        ),
        migrations.AddField(
            model_name='usermodule',
            name='id_annee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee'),
            preserve_default=False,
        ),
    ]
