# Generated by Django 4.2.18 on 2025-05-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0003_alter_periode_etat_periode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='periode',
            field=models.CharField(default=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7'), ('P8', 'P8')], max_length=20),
        ),
    ]
