# Generated by Django 4.2.18 on 2025-05-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0006_alter_deliberation_annuelle_finalite_finalite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliberation_annuelle_resultat',
            name='id_trimestre',
        ),
    ]
