# Generated by Django 4.2.18 on 2025-05-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0008_remove_deliberation_annuelle_condition_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliberation_annuelle_condition',
            name='pourcentage_requis_reussite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.mention'),
        ),
    ]
