# Generated by Django 4.2.18 on 2025-05-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0011_attribution_cours_date_attribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annee_periode',
            name='etat_periode',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En Cours', 'En Cours'), ('Cloturée', 'Cloturée')], default='En attente', max_length=50),
        ),
        migrations.AddField(
            model_name='annee_trimestre',
            name='etat_annee',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En Cours', 'En Cours'), ('Cloturée', 'Cloturée')], default='En attente', max_length=50),
        ),
    ]
