# Generated by Django 4.2.18 on 2025-06-01 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0013_annee_periode_id_trimestre_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annee_periode',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.periode'),
        ),
    ]
