# Generated by Django 4.2.18 on 2025-06-03 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0014_alter_annee_periode_periode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve_inscription',
            name='id_trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee_trimestre'),
        ),
    ]
