# Generated by Django 4.2.18 on 2025-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0026_alter_deliberation_type_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe_cycle_actif',
            name='nbre_classe_par_cycle_actif',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='deliberation_type',
            name='type',
            field=models.CharField(choices=[('Par période', 'Par période'), ('Par trimestre', 'Par trimestre'), ('Par année', 'Par année'), ('Par repêchage', 'Par repêchage')], max_length=200, unique=True),
        ),
    ]
