# Generated by Django 4.2.18 on 2025-07-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0027_classe_cycle_actif_nbre_classe_par_cycle_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe_active',
            name='ordre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
