# Generated by Django 4.2.18 on 2025-07-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0028_classe_active_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe_cycle_actif',
            name='ordre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
