# Generated by Django 4.2.18 on 2025-08-19 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0030_alter_classe_cycle_cycle_alter_classe_cycle_id_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id_banque', models.AutoField(primary_key=True, serialize=False)),
                ('banque', models.CharField(max_length=200)),
                ('sigle', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'recouvrment_banque',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id_compte', models.AutoField(primary_key=True, serialize=False)),
                ('compte', models.CharField(max_length=200)),
                ('id_banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.banque')),
            ],
            options={
                'db_table': 'recouvrment_compte',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id_variable', models.AutoField(primary_key=True, serialize=False)),
                ('variable', models.CharField(max_length=200)),
                ('estObligatoire', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'recouvrment_variable',
            },
        ),
        migrations.CreateModel(
            name='Variable_categorie',
            fields=[
                ('id_variable_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('variable_categorie', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'recouvrment_variable_categorie',
            },
        ),
        migrations.CreateModel(
            name='Variable_prix',
            fields=[
                ('id_prix', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.CharField(max_length=200)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.variable')),
            ],
            options={
                'db_table': 'recouvrment_variable_prix',
            },
        ),
        migrations.CreateModel(
            name='Variable_derogation',
            fields=[
                ('id_datebutoire', models.AutoField(primary_key=True, serialize=False)),
                ('date_butoire', models.DateField()),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.variable')),
            ],
            options={
                'db_table': 'recouvrment_variable_derogation',
            },
        ),
        migrations.CreateModel(
            name='Variable_datebutoire',
            fields=[
                ('id_datebutoire', models.AutoField(primary_key=True, serialize=False)),
                ('date_butoire', models.DateField()),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.variable')),
            ],
            options={
                'db_table': 'recouvrment_variable_datebutoire',
            },
        ),
        migrations.AddField(
            model_name='variable',
            name='id_variable_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.variable_categorie'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.PositiveIntegerField(default=0)),
                ('date_saisie', models.DateField(auto_now_add=True)),
                ('date_paie', models.DateField()),
                ('bordereau', models.FileField(upload_to='')),
                ('status', models.BooleanField(default=False)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe_active', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.compte')),
                ('id_cycle_actif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve_inscription')),
                ('id_variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.variable')),
            ],
            options={
                'db_table': 'recouvrment_paiement',
            },
        ),
        migrations.CreateModel(
            name='Eleve_reduction_prix',
            fields=[
                ('id_reduction_prix', models.AutoField(primary_key=True, serialize=False)),
                ('poucentage', models.PositiveIntegerField()),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve_inscription')),
            ],
            options={
                'db_table': 'recouvrment_reduction_prix',
            },
        ),
    ]
