# Generated by Django 4.2.18 on 2025-08-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0032_rename_variable_categorie_variablecategorie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variablecategorie',
            old_name='variable_categorie',
            new_name='nom',
        ),
    ]
