# Generated by Django 4.2.18 on 2025-08-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0033_rename_variable_categorie_variablecategorie_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve_reduction_prix',
            old_name='id_classe',
            new_name='id_classe_active',
        ),
        migrations.RenameField(
            model_name='eleve_reduction_prix',
            old_name='id_cycle',
            new_name='id_cycle_actif',
        ),
        migrations.RenameField(
            model_name='variabledatebutoire',
            old_name='id_classe',
            new_name='id_classe_active',
        ),
        migrations.RenameField(
            model_name='variabledatebutoire',
            old_name='id_cycle',
            new_name='id_cycle_actif',
        ),
        migrations.RenameField(
            model_name='variablederogation',
            old_name='id_classe',
            new_name='id_classe_active',
        ),
        migrations.RenameField(
            model_name='variablederogation',
            old_name='id_cycle',
            new_name='id_cycle_actif',
        ),
        migrations.RenameField(
            model_name='variableprix',
            old_name='id_classe',
            new_name='id_classe_active',
        ),
        migrations.RenameField(
            model_name='variableprix',
            old_name='id_cycle',
            new_name='id_cycle_actif',
        ),
    ]
