# Generated by Django 4.2.18 on 2025-08-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0035_alter_variableprix_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variablederogation',
            name='id_variable',
        ),
        migrations.AddField(
            model_name='variablederogation',
            name='id_eleve',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classe_deliberation',
            name='showResults',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classe_deliberation',
            name='showsResultsEnOrdre',
            field=models.BooleanField(default=False),
        ),
    ]
