# Generated by Django 4.2.18 on 2025-08-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0037_rename_id_datebutoire_variablederogation_id_derogation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variablederogation',
            old_name='date_butoire',
            new_name='date_derogation',
        ),
    ]
