# Generated by Django 4.2.18 on 2025-08-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0039_eleve_reduction_prix_id_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablederogation',
            name='id_variable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.variable'),
            preserve_default=False,
        ),
    ]
