# Generated by Django 4.2.18 on 2025-08-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0041_alter_eleve_reduction_prix_id_eleve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve_reduction_prix',
            old_name='poucentage',
            new_name='pourcentage',
        ),
    ]
