# Generated by Django 4.2.18 on 2025-08-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0044_paiement_id_banque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='bordereau',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
