# Generated by Django 4.2.18 on 2025-08-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0046_alter_paiement_bordereau'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='bordereau',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
