# Generated by Django 4.2.18 on 2025-08-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0047_paiement_is_rejected_alter_paiement_bordereau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module',
            field=models.CharField(choices=[('Administration', 'Administration'), ('Inscription', 'Inscription'), ('Evaluation', 'Evaluation'), ('Enseignement', 'Enseignement'), ('Institeur et son Espace', 'Institeur et son Espace'), ('Recouvrement', 'Recouvrement'), ('Portail des parents', 'Portail des parents'), ('Archive', 'Archive'), ('Bibliotheque', 'Bibliotheque')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='url_name',
            field=models.CharField(blank=True, choices=[('home_administration', 'home_administration'), ('home_inscription', 'home_inscription'), ('home_evaluation', 'home_evaluation'), ('home_enseignement', 'home_enseignement'), ('home_zone_pedagogique', 'home_zone_pedagogique'), ('home_recouvrement', 'home_recouvrement'), ('home_parent', 'home_parent'), ('home_archive', 'home_archive'), ('home_bibliotheque', 'home_bibliotheque')], max_length=100, null=True),
        ),
    ]
