# Generated by Django 4.2.18 on 2026-01-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0051_alter_periode_periode_alter_trimestre_trimestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id_pays', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du pays')),
                ('sigle', models.CharField(max_length=5, unique=True, verbose_name='Code pays')),
                ('nLevelsStructuraux', models.PositiveIntegerField(default=0, verbose_name='Nombre de niveaux pédagogiques')),
                ('nLevelsAdministratifs', models.PositiveIntegerField(default=0, verbose_name='Nombre de niveaux administratifs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'db_table': 'pays',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='cours_par_classe',
            name='compte_au_nombre_echec',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cours_par_classe',
            name='credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cours_par_classe',
            name='est_considerer_echec_lorsque_pourcentage_est',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cours_par_classe',
            name='heure_semaine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cours_par_classe',
            name='is_obligatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cours_par_classe',
            name='total_considerable_trimestre',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='eleve_note_type',
            name='sigle',
            field=models.CharField(choices=[('T.J', 'T.J'), ('Ex.', 'Ex.'), ('DàD', 'DàD'), ('1e P', '1e P'), ('2e P', '2e P'), ('3e P', '3e P'), ('4e P', '4e P'), ('5e P', '5e P'), ('6e P', '6e P')], max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve_note_type',
            name='type',
            field=models.CharField(choices=[('Travail Journalier', 'Travail Journalier'), ('Examen', 'Examen'), ('Devoir', 'Devoir'), ('1ère Période', '1ère Période'), ('2ème Période', '2ème Période'), ('3ème Période', '3ème Période'), ('4ème Période', '4ème Période'), ('5ème Période', '5ème Période'), ('6ème Période', '6ème Période')], max_length=250),
        ),
        migrations.CreateModel(
            name='StructurePedagogique',
            fields=[
                ('id_structure', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, verbose_name='Code (3 caractères)')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du niveau')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre hiérarchique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures_pedagogiques', to='MonEcole_app.pays', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Structure pédagogique',
                'verbose_name_plural': 'Structures pédagogiques',
                'db_table': 'structuresPedagogiques',
                'ordering': ['pays', 'ordre'],
                'unique_together': {('pays', 'code'), ('pays', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='StructureAdministrative',
            fields=[
                ('id_structure', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, verbose_name='Code (3 caractères)')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du niveau')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre hiérarchique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures_administratives', to='MonEcole_app.pays', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Structure administrative',
                'verbose_name_plural': 'Structures administratives',
                'db_table': 'structuresAdministratives',
                'ordering': ['pays', 'ordre'],
                'unique_together': {('pays', 'code'), ('pays', 'ordre')},
            },
        ),
    ]
