# Generated by Django 4.2.18 on 2026-01-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0052_pays_cours_par_classe_compte_au_nombre_echec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours_par_classe',
            name='ordre_cours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
