# Generated by Django 4.2.18 on 2026-02-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0053_cours_par_classe_ordre_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe_cycle',
            name='cycle',
            field=models.CharField(choices=[('Maternelle', 'Maternelle'), ('Fondamentale', 'Fondamentale'), ('Post Fondamentale', 'Post Fondamentale'), ('Primaire', 'Primaire')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='trimestre',
            field=models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3'), ('Trimestre 4', 'Trimestre 4'), ('Trimestre 5', 'Trimestre 5'), ('Trimestre 6', 'Trimestre 6'), ('Trimestre 7', 'Trimestre 7'), ('Semestre 1', 'Semestre 1'), ('Semestre 2', 'Semestre 2')], max_length=20),
        ),
        migrations.CreateModel(
            name='Deliberation_examen_resultat',
            fields=[
                ('id_deliberation', models.AutoField(primary_key=True, serialize=False)),
                ('pourcentage', models.FloatField()),
                ('place', models.CharField(max_length=200)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve')),
                ('id_periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee_periode')),
                ('id_trimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee_trimestre')),
            ],
            options={
                'verbose_name': 'Résultat de délibération des examen',
                'db_table': 'deliberation_examen_resultats',
            },
        ),
    ]
