# Generated by Django 4.2.18 on 2026-02-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0054_alter_classe_cycle_cycle_alter_trimestre_trimestre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliberation_examen_resultat',
            name='id_periode',
        ),
    ]
