from .form_imports import *
from .instutition_form import *
from .classe_form import *
from .annee_form import *
from .cours_form import *
from .inscription_form import *
from .personnel_form import *
from .module_form import *
from .horaire_form import *
from .evaluation_form import *
from .recouvrement_forms import *
