from MonEcole_app.forms.instutition_form import InstitutionForm,CampusForm
from MonEcole_app.forms.classe_form import ClasseForm,ClasseCycleForm,ClasseCycle_actifForm,Classe_active_Form
from MonEcole_app.forms.annee_form import *
from MonEcole_app.forms.cours_form import *
from MonEcole_app.forms.inscription_form import *
from MonEcole_app.forms.personnel_form import *
from MonEcole_app.forms.module_form import *
from MonEcole_app.forms.horaire_form import *
from MonEcole_app.forms.evaluation_form import *