# Generated by Django 4.2.18 on 2025-08-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'categorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelTable(
            name='categorie',
            table='Biblio_categorie',
        ),
        migrations.AlterModelTable(
            name='emprunt',
            table='Biblio_emprunt',
        ),
        migrations.AlterModelTable(
            name='livre',
            table='Biblio_livre',
        ),
    ]
