# Generated by Django 4.2.18 on 2025-08-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0002_alter_categorie_options_alter_categorie_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='armoire',
            table='Biblio_armoire',
        ),
        migrations.AlterModelTable(
            name='compartiment',
            table='Biblio_compartiment',
        ),
    ]
