# Generated by Django 4.2.18 on 2025-08-11 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_manager', '0003_alter_armoire_table_alter_compartiment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('peut_emprunter', models.BooleanField(default=True)),
                ('limite_emprunts', models.PositiveIntegerField(default=3)),
            ],
            options={
                'db_table': 'Biblio_empruteur_role',
            },
        ),
        migrations.AddField(
            model_name='livre',
            name='etat',
            field=models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon'), ('USÉ', 'Usé'), ('ENDOMMAGÉ', 'Endommagé')], default='NEUF', max_length=50),
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='library_manager.role')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
                'db_table': 'Biblio_empruteur_profile',
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('AJOUT', 'Ajout'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('EMPRUNT', 'Emprunt'), ('RETOUR', 'Retour')], max_length=20)),
                ('objet', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques', to='library_manager.profilutilisateur')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historiques',
                'db_table': 'Biblio_historique',
            },
        ),
    ]
