# Generated by Django 4.2.18 on 2025-08-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonEcole_app', '0048_alter_module_module_alter_module_url_name'),
        ('library_manager', '0004_role_livre_etat_profilutilisateur_historique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='id_annee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.annee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprunt',
            name='id_campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.campus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprunt',
            name='id_classe_active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_active'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='id_cycle_actif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.classe_cycle_actif'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='id_eleve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.eleve'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='id_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MonEcole_app.personnel'),
        ),
        migrations.AlterField(
            model_name='armoire',
            name='localisation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Historique',
        ),
    ]
