# Generated by Django 4.2.18 on 2025-08-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0006_remove_profilutilisateur_date_inscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='library_manager.categorie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livre',
            name='compartiment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='library_manager.compartiment'),
            preserve_default=False,
        ),
    ]
