# Generated by Django 4.2.18 on 2025-08-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0007_alter_livre_categorie_alter_livre_compartiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='nombre_exemplaires',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventaire', models.CharField(max_length=50, unique=True)),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('USE', 'Usé')], max_length=50)),
                ('disponible', models.BooleanField(default=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_manager.livre')),
            ],
        ),
    ]
