# Generated by Django 4.2.18 on 2025-08-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0008_livre_nombre_exemplaires_exemplaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprunt',
            old_name='livre',
            new_name='id_livre',
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='etat',
            field=models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon'), ('USÉ', 'Usé'), ('ENDOMMAGÉ', 'Endommagé')], default='BON', max_length=50),
        ),
        migrations.AlterField(
            model_name='livre',
            name='etat',
            field=models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon'), ('USÉ', 'Usé'), ('ENDOMMAGÉ', 'Endommagé')], default='BON', max_length=50),
        ),
    ]
