# Generated by Django 4.2.18 on 2025-08-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0009_rename_livre_emprunt_id_livre_alter_exemplaire_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
