# Generated by Django 4.2.18 on 2025-08-11 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Armoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('localisation', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Biblio_armoire',
                'verbose_name_plural': 'Armoires',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Biblio_categorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Compartiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('capacite', models.PositiveIntegerField(default=10)),
                ('armoire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library_manager.armoire')),
            ],
            options={
                'verbose_name': 'Biblio_compartiment',
                'verbose_name_plural': 'Compartiments',
                'unique_together': {('armoire', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres', to='library_manager.categorie')),
                ('compartiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres', to='library_manager.compartiment')),
            ],
            options={
                'verbose_name': 'Biblio_livre',
                'verbose_name_plural': 'Livres',
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('rendu', models.BooleanField(default=False)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to='library_manager.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biblio_emprunt',
                'verbose_name_plural': 'Emprunts',
            },
        ),
    ]
