# Generated by Django 4.2.18 on 2025-08-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0005_remove_emprunt_utilisateur_emprunt_id_annee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='date_inscription',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='profile',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
